### ISSUE TITLE
TEST Lamdas Functionality

### ISSUE THREAD

**Issue by keggyy** [arduosoft/RawCMS#195]
Test and improve Lambdas functionality (Lambdas are created for work with external system)
![2020-02-08 08_56_11-Raw CMS GUI](https://user-images.githubusercontent.com/17206853/74081590-f9fa7000-4a50-11ea-965c-87d35186d3ba.png)

- [ ] Write lambda for reads data from an external system

- [ ] Write lambda for call internal API and save your external data

- [ ] Improve documentation with examples

Any improvement suggestions extending this functionality is well accepted.

**Comment by tokarzkj** [comment]
@zeppaman - This was the issue I was interested in working on.

**Comment by zeppaman** [comment]
Assigned!
I have some questions for @keggyy to complete the task description. The todo's inside the task are just the final test. But we need to add the capabilities of using internal API (CrudService) to write internal data, because atm only the HTTP client is available. I'm right? Or, for this test, you planned to use the plain HTTP client? In this case, the snippet inside the public demo can be used as a reference.

**Comment by keggyy** [comment]
In this task, we can do only the test of Lambdas functionality. Then @tokarzkj , you can use snippet on a public demo like references and use the plain HTTP client for call internal API.
About integration with CrudService, I prepare now a new task for Kris

**Comment by tokarzkj** [comment]
@keggyy - Okay, I have played around with Lambdas a little and think I understand. The idea to write a unit test to confirm that Lambdas work. Am I writing tests on the front end or is this in the back end?

**Comment by keggyy** [comment]
Hi @tokarzkj, write your test on frontend and add it on documentation if is possibile. Thi is sufficient for close task.
